<?php
/**
 * The Front-End Dashboard for the Standalone Screener Application.
 * This script is the public web page. It is designed to be extremely fast.
 * It reads pre-calculated JSON data from the cache and renders it.
 * It makes NO API calls.
 *
 * @since      1.0.0 (Standalone)
 */
date_default_timezone_set('UTC');

function read_cache_file($filename) {
    $filepath = __DIR__ . '/cache/' . $filename;
    if (file_exists($filepath)) {
        return json_decode(file_get_contents($filepath), true);
    }
    return [];
}

// Read all the data generated by the worker.
$magic_formula_data = read_cache_file('magic_formula.json');
$piotroski_data = read_cache_file('piotroski.json');
$value_scan_data = read_cache_file('value_scan.json');
$live_quotes = read_cache_file('live_quotes.json');

// Get the last modified time of a cache file to show when data was last updated.
$cache_file_path = __DIR__ . '/cache/magic_formula.json';
$last_updated = file_exists($cache_file_path) ? filemtime($cache_file_path) : null;
$last_updated_string = $last_updated ? 'Data last updated: ' . date('Y-m-d H:i T', $last_updated) : 'Data is being generated. Please check back soon.';

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Investment Screener Dashboard</title>
    <style>
        /* All the CSS from our prototype goes here */
        :root {
            --bg-color: #1a1a2e; --surface-color: #16213e; --primary-color: #0f3460;
            --accent-color: #537895; --text-color: #e3e3e3; --text-muted-color: #a0a0a0;
            --positive-color: #26a69a; --negative-color: #ef5350;
        }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif; background-color: var(--bg-color); color: var(--text-color); margin: 0; padding: 20px; }
        .dashboard-container { max-width: 1200px; margin: 0 auto; padding: 20px; background-color: var(--surface-color); border-radius: 12px; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3); }
        header { border-bottom: 1px solid var(--primary-color); padding-bottom: 15px; margin-bottom: 25px; }
        header h1 { margin: 0; color: #fff; font-size: 1.8em; }
        header p { margin: 5px 0 0 0; color: var(--text-muted-color); }
        .tabs { display: flex; gap: 10px; border-bottom: 2px solid var(--primary-color); }
        .tab-link { padding: 12px 25px; cursor: pointer; border: none; background-color: transparent; color: var(--text-muted-color); font-size: 1.1em; font-weight: 500; border-bottom: 3px solid transparent; transition: all 0.2s ease-in-out; }
        .tab-link:hover { color: #fff; }
        .tab-link.active { color: #fff; border-bottom-color: var(--accent-color); }
        .tab-content-container { padding-top: 25px; }
        .tab-content { display: none; animation: fadeIn 0.5s; }
        .tab-content.active { display: block; }
        .screener-wrapper { overflow-x: auto; }
        .screener-table { width: 100%; border-collapse: collapse; font-size: 0.95em; }
        .screener-table thead tr { background-color: var(--primary-color); text-align: left; }
        .screener-table th, .screener-table td { padding: 14px 16px; }
        .screener-table tbody tr { border-bottom: 1px solid var(--primary-color); transition: background-color 0.2s ease; }
        .screener-table tbody tr:last-of-type { border-bottom: none; }
        .screener-table tbody tr:hover { background-color: rgba(15, 52, 96, 0.5); }
        .screener-table td:first-child, .screener-table th:first-child { font-weight: bold; }
        .positive-change { color: var(--positive-color); }
        .negative-change { color: var(--negative-color); }
        @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
    </style>
</head>
<body>

    <div class="dashboard-container">
        <header>
            <h1>Investment Screener Dashboard</h1>
            <p><?php echo htmlspecialchars($last_updated_string); ?></p>
        </header>

        <main>
            <div class="tabs">
                <button class="tab-link active" data-screener="magic_formula">Magic Formula</button>
                <button class="tab-link" data-screener="piotroski">Piotroski Scan</button>
                <button class="tab-link" data-screener="value_scan">Value Scan (Graham)</button>
            </div>

            <div class="tab-content-container">
                <div id="content-magic_formula" class="tab-content active">
                    <?php if (empty($magic_formula_data)): ?>
                        <p>No Magic Formula data available. The background worker may not have run yet.</p>
                    <?php else: ?>
                        <div class="screener-wrapper">
                            <table class="screener-table">
                                <thead><tr><th>Rank</th><th>Company</th><th>Symbol</th><th>Price</th><th>Change</th><th>Earnings Yield</th><th>Return on Capital</th></tr></thead>
                                <tbody>
                                    <?php foreach($magic_formula_data as $index => $stock):
                                        $quote = $live_quotes[$stock['symbol']] ?? null;
                                        $price = $quote ? number_format($quote['price'], 2) : '--';
                                        $change = $quote ? $quote['change'] : 0;
                                        $change_p = $quote ? $quote['changesPercentage'] : 0;
                                        $change_class = $change > 0 ? 'positive-change' : ($change < 0 ? 'negative-change' : '');
                                    ?>
                                    <tr>
                                        <td><?php echo $index + 1; ?></td>
                                        <td><?php echo htmlspecialchars($stock['name']); ?></td>
                                        <td><?php echo htmlspecialchars($stock['symbol']); ?></td>
                                        <td><?php echo $price; ?></td>
                                        <td class="<?php echo $change_class; ?>"><?php echo $quote ? number_format($change, 2) . ' (' . number_format($change_p, 2) . '%)' : '--'; ?></td>
                                        <td><?php echo number_format($stock['earnings_yield'] * 100, 2); ?>%</td>
                                        <td><?php echo number_format($stock['return_on_capital'] * 100, 2); ?>%</td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    <?php endif; ?>
                </div>

                <div id="content-piotroski" class="tab-content">
                     <?php if (empty($piotroski_data)): ?>
                        <p>No high-scoring Piotroski stocks found. The background worker may not have run yet.</p>
                    <?php else: ?>
                        <div class="screener-wrapper">
                            <table class="screener-table">
                                <thead><tr><th>Rank</th><th>Company</th><th>Symbol</th><th>Price</th><th>Change</th><th>F-Score</th></tr></thead>
                                <tbody>
                                    <?php foreach($piotroski_data as $index => $stock):
                                        $quote = $live_quotes[$stock['symbol']] ?? null;
                                        $price = $quote ? number_format($quote['price'], 2) : '--';
                                        $change = $quote ? $quote['change'] : 0;
                                        $change_p = $quote ? $quote['changesPercentage'] : 0;
                                        $change_class = $change > 0 ? 'positive-change' : ($change < 0 ? 'negative-change' : '');
                                    ?>
                                    <tr>
                                        <td><?php echo $index + 1; ?></td>
                                        <td><?php echo htmlspecialchars($stock['name']); ?></td>
                                        <td><?php echo htmlspecialchars($stock['symbol']); ?></td>
                                        <td><?php echo $price; ?></td>
                                        <td class="<?php echo $change_class; ?>"><?php echo $quote ? number_format($change, 2) . ' (' . number_format($change_p, 2) . '%)' : '--'; ?></td>
                                        <td><?php echo htmlspecialchars($stock['f_score']); ?> / 9</td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    <?php endif; ?>
                </div>

                <div id="content-value_scan" class="tab-content">
                    <?php if (empty($value_scan_data)): ?>
                        <p>No stocks met the Graham Value criteria. The background worker may not have run yet.</p>
                    <?php else: ?>
                        <div class="screener-wrapper">
                            <table class="screener-table">
                                <thead><tr><th>Rank</th><th>Company</th><th>Symbol</th><th>Price</th><th>Change</th><th>P/E Ratio</th><th>P/B Ratio</th><th>Current Ratio</th></tr></thead>
                                <tbody>
                                     <?php foreach($value_scan_data as $index => $stock):
                                        $quote = $live_quotes[$stock['symbol']] ?? null;
                                        $price = $quote ? number_format($quote['price'], 2) : '--';
                                        $change = $quote ? $quote['change'] : 0;
                                        $change_p = $quote ? $quote['changesPercentage'] : 0;
                                        $change_class = $change > 0 ? 'positive-change' : ($change < 0 ? 'negative-change' : '');
                                    ?>
                                    <tr>
                                        <td><?php echo $index + 1; ?></td>
                                        <td><?php echo htmlspecialchars($stock['name']); ?></td>
                                        <td><?php echo htmlspecialchars($stock['symbol']); ?></td>
                                        <td><?php echo $price; ?></td>
                                        <td class="<?php echo $change_class; ?>"><?php echo $quote ? number_format($change, 2) . ' (' . number_format($change_p, 2) . '%)' : '--'; ?></td>
                                        <td><?php echo number_format($stock['pe_ratio'], 2); ?></td>
                                        <td><?php echo number_format($stock['pb_ratio'], 2); ?></td>
                                        <td><?php echo number_format($stock['current_ratio'], 2); ?></td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </main>
    </div>

    <script>
        // Simple, efficient JavaScript for tab switching. No AJAX needed.
        document.addEventListener('DOMContentLoaded', () => {
            const tabs = document.querySelectorAll('.tab-link');
            const contentAreas = document.querySelectorAll('.tab-content');

            tabs.forEach(tab => {
                tab.addEventListener('click', (event) => {
                    const screenerId = event.currentTarget.dataset.screener;
                    tabs.forEach(t => t.classList.remove('active'));
                    contentAreas.forEach(c => c.classList.remove('active'));
                    event.currentTarget.classList.add('active');
                    document.getElementById(`content-${screenerId}`).classList.add('active');
                });
            });
        });
    </script>

</body>
</html>